### ISSUE TITLE
Orders service throws exception, returns 500 when param is missing/null

### ISSUE THREAD

**Issue by idcrosby** [microservices-demo/microservices-demo#197]
Should handle gracefully and return 400 level error

```
orders_1        | 2016-08-02 09:19:13.816 ERROR 1 --- [p-nio-80-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalStateException: Unable to create order due to unspecified IO error.] with root cause

java.lang.IllegalArgumentException: 'url' must not be null
orders_1        |   at org.springframework.util.Assert.notNull(Assert.java:115) ~[spring-core-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
orders_1        |   at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:588) ~[spring-web-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
orders_1        |   at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572) ~[spring-web-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
orders_1        |   at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:546) ~[spring-web-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
orders_1        |   at works.weave.socks.orders.services.AsyncGetService.getResource(AsyncGetService.java:58) ~[app.jar!/:0.0.1-SNAPSHOT]
orders_1        |   at works.weave.socks.orders.services.AsyncGetService$$FastClassBySpringCGLIB$$2bee767d.invoke(<generated>) ~[app.jar!/:0.0.1-SNAPSHOT]
orders_1        |   at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
orders_1        |   at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720) ~[spring-aop-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
orders_1        |   at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
orders_1        |   at org.springframework.aop.interceptor.AsyncExecutionInterceptor$1.call(AsyncExecutionInterceptor.java:115) ~[spring-aop-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
orders_1        |   at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_92-internal]
orders_1        |   at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92-internal]
```

**Comment by philwinder** [comment]
See https://github.com/microservices-demo/orders/issues/11
