### ISSUE TITLE
front-end: Crash when catalogue not found

### ISSUE THREAD

**Issue by philwinder** [microservices-demo/microservices-demo#205]
Strange one, but caused by the catalogue not being found. Fond on Mesos-cni deploy.

front-end:

```
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: getaddrinfo ENOTFOUND catalogue.mesos-executeinstance.weave.local catalogue.mesos-executeinstance.weave.local:80
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:79:26)
```

But prior to this crash, the front-end was successful in communicating with the catalogue. Catalogue logged access:

```
ts=2016-08-01T11:18:14Z caller=main.go:73 transport=HTTP port=80
ts=2016-08-01T11:32:34Z caller=middlewares.go:38 method=List tags= order=id pageNum=1 pageSize=5 result=5 took=12.944µs
```

And, the catalogue is still present in the DNS:

```
VERY VERBOSE: 2016/08/01 11:33:48 generator.go:601: [A] catalogue.mesos-executeinstance.weave.local.: 10.42.0.5
```

So failure to get catalogue, but don't know why.

**Comment by pidster** [comment]
We should look at circuit breakers.

**Comment by philwinder** [comment]
Fixed in https://github.com/microservices-demo/front-end/pull/18
