### ISSUE TITLE
Another UI crash - catalogue not found

### ISSUE THREAD

**Issue by philwinder** [microservices-demo/microservices-demo#219]
Crashed upon catalogue timeout. Shouldn't crash, just error.

```
+ /usr/libexec/mesos/mesos-containerizer mount --help=false --operation=make-rslave --path=/
+ mount -n --rbind /var/lib/mesos/slaves/ab0b65ca-23d9-4a85-aff8-9bdab6d0e39e-S2/frameworks/ab0b65ca-23d9-4a85-aff8-9bdab6d0e39e-0095/executors/front-end/runs/85e0c3fe-def3-43fd-8618-47338939c3f9 /var/lib/mesos/provisioner/containers/85e0c3fe-def3-43fd-8618-47338939c3f9/backends/copy/rootfses/10d8f67d-305f-4986-942a-f31b7ba19ec7/mnt/mesos/sandbox
I0804 12:33:03.552575 30355 exec.cpp:161] Version: 1.0.0
I0804 12:33:03.553678 30359 exec.cpp:236] Executor registered on agent ab0b65ca-23d9-4a85-aff8-9bdab6d0e39e-S2
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: getaddrinfo ENOTFOUND catalogue.mesos-executeinstance.weave.local catalogue.mesos-executeinstance.weave.local:80
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:79:26)
```

**Comment by philwinder** [comment]
I can seem to recreate this on mesos by firing two catalogue requests one after the other. E.g.

```
curl -v http://ec2-52-59-112-208.eu-central-1.compute.amazonaws.com/catalogue/images/holy_1.jpeg
curl -v http://ec2-52-59-112-208.eu-central-1.compute.amazonaws.com/catalogue/images/holy_1.jpeg
```

But it might be due to DNS tardiness, not the front-end service directly.

**Comment by philwinder** [comment]
I believe this was due to nginx. If I removed the dynamic config I was attempting, then it worked perfectly. 
But this doesn't remove the fact that it crashed when a call failed, rather than just errored.

**Comment by philwinder** [comment]
Fixed in https://github.com/microservices-demo/front-end/pull/18
