### ISSUE TITLE
Sock Shop deployed to Docker Swarm does not work

### ISSUE THREAD

**Issue by mongrelion** [microservices-demo/microservices-demo#717]
## The Problem
As someone reported on the [Weave Users](weave-community.slack.com/) Slack group, the deployment with Docker Swarm is broken.

Here's a screenshot of how it looks when trying to access the shop via the browser:
<img width="1136" alt="swarm001" src="https://user-images.githubusercontent.com/196122/26886777-94c83d6c-4ba6-11e7-8a13-1b441b4fb46a.png">

To reproduce the error one simply needs to follow our [official guide to deploy the Sock Shop to Docker Swarm](https://microservices-demo.github.io/microservices-demo/deployment/docker-swarm.html)

Setting up Docker Swarm, bundling the shop with Docker Compose and deploying the service works good. It's only during runtime that one gets this error.

## Errors
When querying the *catalogue* service, this is the response:
```
$ curl http://localhost:30000/catalogue?size=5
{"message":"getaddrinfo ENOTFOUND catalogue catalogue:80","error":{"code":"ENOTFOUND","errno":"ENOTFOUND","syscall":"getaddrinfo","hostname":"catalogue","host":"catalogue","port":80}}
```

A similar error is returned for the *cart* service
```
$ curl http://localhost:30000/cart
{"message":"getaddrinfo ENOTFOUND carts carts:80","error":{"code":"ENOTFOUND","errno":"ENOTFOUND","syscall":"getaddrinfo","hostname":"carts","host":"carts","port":80}}
````

## Specs
My system:
```
macOS Sierra 10.12.4
$ docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by mongrelion** [comment]
Further, deploying the Sock Shop to Docker Compose using Weave, the service does seem to come up nicely, but the **user-sim** run fails at some point:

```
user-sim_1      | Locust file: /config/locustfile.py
user-sim_1      | Will run /config/locustfile.py against edge-router. Spawning 2 clients and 200 total requests.
user-sim_1      | [2017-06-07 16:00:41,669] user-simulator.weave.local/INFO/locust.main: Starting Locust 0.7.5
user-sim_1      | [2017-06-07 16:00:41,670] user-simulator.weave.local/INFO/locust.runners: Hatching and swarming 2 clients at the rate 5 clients/s...
user-sim_1      | [2017-06-07 16:00:42,071] user-simulator.weave.local/INFO/locust.runners: All locusts hatched: Web: 2
user-sim_1      | [2017-06-07 16:00:42,071] user-simulator.weave.local/INFO/locust.runners: Resetting stats
user-sim_1      |
user-sim_1      | [2017-06-07 16:00:47,427] user-simulator.weave.local/INFO/locust.runners: All locusts dead
user-sim_1      |
user-sim_1      | [2017-06-07 16:00:47,427] user-simulator.weave.local/INFO/locust.main: Shutting down (exit code 1), bye.
user-sim_1      |  Name                                                          # reqs      # fails     Avg     Min     Max  |  Median   req/s
user-sim_1      | --------------------------------------------------------------------------------------------------------------------------------------------
user-sim_1      |  GET /                                                             21     0(0.00%)       5       4       9  |       5    2.33
user-sim_1      |  GET /basket.html                                                  22     0(0.00%)       5       4       9  |       5    2.67
user-sim_1      |  DELETE /cart                                                      23     0(0.00%)      18      10      35  |      18    2.67
user-sim_1      |  POST /cart                                                        23     0(0.00%)      66      21     263  |      40    2.67
user-sim_1      |  GET /catalogue                                                    21     0(0.00%)      23       7      63  |      12    2.33
user-sim_1      |  GET /category.html                                                23     0(0.00%)       5       4      11  |       5    2.67
user-sim_1      |  GET /detail.html?id=03fef6ac-1896-4ce8-bd69-b798f85c6e0b           3     0(0.00%)       6       5       8  |       5    0.33
user-sim_1      |  GET /detail.html?id=3395a43e-2d88-40de-b95f-e00e1502085b           1     0(0.00%)       9       9       9  |       9    0.33
user-sim_1      |  GET /detail.html?id=510a0d7e-8e83-4193-b483-e27e09ddc34d           2     0(0.00%)       4       4       4  |       4    0.67
user-sim_1      |  GET /detail.html?id=808a2de1-1aaa-4c25-a9b9-6612e8f29a38           1     0(0.00%)       4       4       4  |       4    0.00
user-sim_1      |  GET /detail.html?id=819e1fbf-8b7e-4f6d-811f-693534916a8b           2     0(0.00%)       4       4       5  |       4    0.00
user-sim_1      |  GET /detail.html?id=837ab141-399e-4c1f-9abc-bace40296bac           4     0(0.00%)       5       4       7  |       4    0.00
user-sim_1      |  GET /detail.html?id=a0a4f044-b040-410d-8ead-4de0446aec7e           3     0(0.00%)       5       4       6  |       5    0.67
user-sim_1      |  GET /detail.html?id=d3588630-ad8e-49df-bbd7-3167f7efb246           3     0(0.00%)       6       4       8  |       7    0.33
user-sim_1      |  GET /detail.html?id=zzz4f044-b040-410d-8ead-4de0446aec7e           4     0(0.00%)      15       4      43  |       6    0.33
user-sim_1      |  GET /login                                                        23     0(0.00%)      98      60     451  |      73    2.67
user-sim_1      |  POST /orders                                                      20     1(4.76%)     282     125    1255  |     160    2.33
user-sim_1      | --------------------------------------------------------------------------------------------------------------------------------------------
user-sim_1      |  Total                                                            199     1(0.50%)                                      23.00
user-sim_1      |
user-sim_1      | Percentage of the requests completed within given times
user-sim_1      |  Name                                                           # reqs    50%    66%    75%    80%    90%    95%    98%    99%   100%
user-sim_1      | --------------------------------------------------------------------------------------------------------------------------------------------
user-sim_1      |  GET /                                                              21      5      5      7      7      8      8      9      9      9
user-sim_1      |  GET /basket.html                                                   22      5      5      6      6      7      7      9      9      9
user-sim_1      |  DELETE /cart                                                       23     18     20     22     22     27     30     35     35     35
user-sim_1      |  POST /cart                                                         23     40     54     58     80    190    260    260    260    263
user-sim_1      |  GET /catalogue                                                     21     12     15     48     49     59     59     63     63     63
user-sim_1      |  GET /category.html                                                 23      5      6      7      7      9     10     11     11     11
user-sim_1      |  GET /detail.html?id=03fef6ac-1896-4ce8-bd69-b798f85c6e0b            3      5      5      8      8      8      8      8      8      8
user-sim_1      |  GET /detail.html?id=3395a43e-2d88-40de-b95f-e00e1502085b            1      9      9      9      9      9      9      9      9      9
user-sim_1      |  GET /detail.html?id=510a0d7e-8e83-4193-b483-e27e09ddc34d            2      4      4      4      4      4      4      4      4      4
user-sim_1      |  GET /detail.html?id=808a2de1-1aaa-4c25-a9b9-6612e8f29a38            1      4      4      4      4      4      4      4      4      4
user-sim_1      |  GET /detail.html?id=819e1fbf-8b7e-4f6d-811f-693534916a8b            2      5      5      5      5      5      5      5      5      5
user-sim_1      |  GET /detail.html?id=837ab141-399e-4c1f-9abc-bace40296bac            4      6      6      7      7      7      7      7      7      7
user-sim_1      |  GET /detail.html?id=a0a4f044-b040-410d-8ead-4de0446aec7e            3      5      5      6      6      6      6      6      6      6
user-sim_1      |  GET /detail.html?id=d3588630-ad8e-49df-bbd7-3167f7efb246            3      7      7      8      8      8      8      8      8      8
user-sim_1      |  GET /detail.html?id=zzz4f044-b040-410d-8ead-4de0446aec7e            4      8      8     43     43     43     43     43     43     43
user-sim_1      |  GET /login                                                         23     73     80     83     88     95    250    450    450    451
user-sim_1      |  POST /orders                                                       20    160    180    230    280   1200   1300   1300   1300   1255
user-sim_1      | --------------------------------------------------------------------------------------------------------------------------------------------
user-sim_1      |
user-sim_1      | Error report
user-sim_1      |  # occurences       Error
user-sim_1      | --------------------------------------------------------------------------------------------------------------------------------------------
user-sim_1      |  1                  POST /orders: "HTTPError(u'406 Client Error: Not Acceptable for url: http://edge-router/orders',)"
user-sim_1      | --------------------------------------------------------------------------------------------------------------------------------------------
user-sim_1      |
user-sim_1      | done
```

Weird because from the browser I was able to place an order in the Shop.

**Comment by mongrelion** [comment]
@vlal you're a little more familiar than me on this area. Would you know top of your mind after a quick glance why this is not working as expected?

**Comment by patrickse** [comment]
I´ve got the same behaviour with kubernetes... the carts and catalogue services can´t find their databases...

```

com.mongodb.MongoSocketException: carts-db: Try again
        at com.mongodb.ServerAddress.getSocketAddress(ServerAddress.java:188) ~[mongodb-driver-core-3.2.2.jar!/:na]
        at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:50) ~[mongodb-driver-core-3.2.2.jar!/:na]
        at com.mongodb.connection.SocketStream.open(SocketStream.java:58) ~[mongodb-driver-core-3.2.2.jar!/:na]
        at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:114) ~[mongodb-driver-core-3.2.2.jar!/:na]
        at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:128) ~[mongodb-driver-core-3.2.2.jar!/:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111-internal]
Caused by: java.net.UnknownHostException: carts-db: Try again
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[na:1.8.0_111-internal]
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928) ~[na:1.8.0_111-internal]
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323) ~[na:1.8.0_111-internal]
        at java.net.InetAddress.getAllByName0(InetAddress.java:1276) ~[na:1.8.0_111-internal]
        at java.net.InetAddress.getAllByName(InetAddress.java:1192) ~[na:1.8.0_111-internal]
        at java.net.InetAddress.getAllByName(InetAddress.java:1126) ~[na:1.8.0_111-internal]
        at java.net.InetAddress.getByName(InetAddress.java:1076) ~[na:1.8.0_111-internal]
        at com.mongodb.ServerAddress.getSocketAddress(ServerAddress.java:186) ~[mongodb-driver-core-3.2.2.jar!/:na]
        ... 5 common frames omitted
```

```
ts=2017-06-13T11:49:03Z caller=main.go:108 Error="Unable to connect to Database" DSN=catalogue_user:default_password@tcp(catalogue-db:3306)/socksdb
```

**Comment by cmendesce** [comment]
Hi @mongrelion 

I had the same problem before. I solved that by setting the `associate_public_ip_address = true` in my `aws_instance`.

**Comment by mongrelion** [comment]
@cmendesce Great to know that you got it working!
However, this is also present when deploying to a local instance of Docker :C

**Comment by pidster** [comment]
For future reference: if anyone runs into this issue, please check that all of the containers/services are up and running. The `user-sim` container can start before the other services are ready.

**Comment by dylannil** [comment]
With kubernetes，DNS(e.g. CoreDNS) seems like to be necesary.

**Comment by keltik85** [comment]
`root@my-pc~# microk8s.enable dns` made it work

**Comment by oumkale** [comment]
Hello @pidster, @keltik85, @muhonglong , @mongrelion, @patrickse,
I am facing the similar problem, but with API requests. Not able to send GET and POST  requests on orders and POST requests on carts. 
```
from locust import HttpLocust, TaskSet, task, HttpUser
from random import randint, choice
import base64
import time
import uuid
               	
counter = 0
customer_id = ""
class APITasks(TaskSet):
	@task
	def on_start(self):
	    self.login()

	@task
	def purchaseItem(self):
		self.login()
		self.buy()
		
	@task
	def addRemoveFromCart(self):
		self.createCustomer()
		self.login()
		
	@task
	def buy(self):
		base64_str = base64.encodebytes(('%s:%s' % ("user","password")).encode()).decode().strip()
		login = self.client.get("/login", headers={"Authorization":"Basic %s" % base64_str})
		self.cust_id = login.cookies["logged_in"]
		cookie = {'logged_in': self.cust_id}
		orde = self.client.get("http://3.8.78.2:30001/orders/", cookies=cookie, catch_response=True)
		print("Orders responce :",orde)
		self.client.post("http://3.8.78.2:30001/orders/", cookies=cookie)
		time.sleep(2.0)

	def login(self):
		base64_str = base64.encodebytes(('%s:%s' % ("user","password")).encode()).decode().strip()
		login = self.client.get("http://3.8.78.2:30001/login", headers={"Authorization":"Basic %s" % base64_str})
		self.cust_id = login.cookies["logged_in"]
		customer_id = login.cookies["logged_in"]
		time.sleep(2.0)
	@task
	def createCustomer(self):
		
		global counter
		counter += 1
		self.username = "test_user_" + str(uuid.uuid4())

		self.password = "test_password"
		customer = self.client.post("http://3.8.78.2:30001/register", json={"username": self.username, "password": self.password}).json()
		print("Customer---> :", customer["id"])
		self.cust_id = customer["id"]
		customer_id = self.cust_id
		time.sleep(2.0)


class Web(HttpUser):
    tasks = [APITasks]
    min_wait = 0
    max_wait = 0
```
Response can be:
Orders responce : <Response [0]>
Orders responce : <Response [0]>
Orders responce : <Response [201]>
Orders responce : <Response [0]>
Orders responce : <Response [0]>
Orders responce : <Response [500]>
Orders responce : <Response [500]>
Causing :
```
front-end-5d96ff485b-5t87x      0/1     CrashLoopBackOff   4          27m
front-end-5d96ff485b-njf8d      0/1     CrashLoopBackOff   4          27m
orders-5587cf86d7-j7c7f         1/1     Running            6          5h35m
orders-5587cf86d7-wzbwz         0/1     Running 
```

Inside front-end logs : POST /orders 500 1031.215 ms - 164
