### ISSUE TITLE
Can't launch demo tests are running and one seems to be looping

### ISSUE THREAD

**Issue by abuehrle** [microservices-demo/microservices-demo#721]
docker-compose version: 

```docker-compose version 1.11.2, build dfed245```

Docker for mac versions: 

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64
```
```
Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

Launching the demo with Docker for Mac and docker-compose results in a loop in one of the tests and doesn't launch: 

```POST /customers 200 4.553 ms - -
front-end_1     | Request received with body: {}
front-end_1     | Error: User not logged in.
front-end_1     |     at /usr/src/app/api/orders/index.js:52:13
front-end_1     |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
front-end_1     |     at next (/usr/src/app/node_modules/express/lib/router/route.js:131:13)
front-end_1     |     at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)
front-end_1     |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
front-end_1     |     at /usr/src/app/node_modules/express/lib/router/index.js:277:22
front-end_1     |     at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:330:12)
front-end_1     |     at next (/usr/src/app/node_modules/express/lib/router/index.js:271:10)
front-end_1     |     at expressInit (/usr/src/app/node_modules/express/lib/middleware/init.js:33:5)
front-end_1     |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
front-end_1     | POST /orders 500 1.561 ms - 22
```

**Comment by pidster** [comment]
See also: https://github.com/microservices-demo/microservices-demo/issues/717
