### ISSUE TITLE
Error "java.net.UnknownHostException: carts-db: Try again" on kuberenetes setup

### ISSUE THREAD

**Issue by amar123deep** [microservices-demo/microservices-demo#735]
- Add labels appropriate to the issue 
kubeadm version v1.7.3
Newtork plugin weave net 
- Describe the expected behaviour and the actual behaviour
Carts-db should have been found as it is deployed correctly. 
- Describe steps to reproduce the problem
1. Setup kubernetes cluster 
2. install weave net plugin 
3. create sock-shop namespace using "kubectl create namespace sock-shop"
4. deploy sock-shop either using manifest files or complete-demo.yml file, e.g. "kubectl apply -f complete-demo.yaml"
5. run the command "kubectl get logs carts-container-name-in-your-setup -n sock-shop"
2017-08-17 12:17:01.137  INFO [carts,,,] 13 --- [-carts-db:27017] org.mongodb.driver.cluster               : Exception in monitor thread while connecting to server carts-db:27017

com.mongodb.MongoSocketException: carts-db: Try again
	at com.mongodb.ServerAddress.getSocketAddress(ServerAddress.java:188) ~[mongodb-driver-core-3.2.2.jar!/:na]
	at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:50) ~[mongodb-driver-core-3.2.2.jar!/:na]
	at com.mongodb.connection.SocketStream.open(SocketStream.java:58) ~[mongodb-driver-core-3.2.2.jar!/:na]
	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:114) ~[mongodb-driver-core-3.2.2.jar!/:na]
	at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:128) ~[mongodb-driver-core-3.2.2.jar!/:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111-internal]
Caused by: java.net.UnknownHostException: carts-db: Try again
	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method) ~[na:1.8.0_111-internal]
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928) ~[na:1.8.0_111-internal]
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323) ~[na:1.8.0_111-internal]
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276) ~[na:1.8.0_111-internal]
	at java.net.InetAddress.getAllByName(InetAddress.java:1192) ~[na:1.8.0_111-internal]
	at java.net.InetAddress.getAllByName(InetAddress.java:1126) ~[na:1.8.0_111-internal]
	at java.net.InetAddress.getByName(InetAddress.java:1076) ~[na:1.8.0_111-internal]
	at com.mongodb.ServerAddress.getSocketAddress(ServerAddress.java:186) ~[mongodb-driver-core-3.2.2.jar!/:na]
	... 5 common frames omitted

**Comment by amar123deep** [comment]
also the front-end access using http://<master_ip>:30001 shows similar to shown in the issue **[717](https://github.com/microservices-demo/microservices-demo/issues/717)**.

**Comment by embs** [comment]
Hi @amar123deep.

I've faced a similar problem and worked around it by deploying with the [complete-demo](https://github.com/microservices-demo/microservices-demo/blob/c0b9aa6f462ddfb776fa57a3274c12d0c051d45d/deploy/kubernetes/complete-demo.yaml). It's usage is documented in [Deploying Sock Shop on any Kubernetes cluster](https://microservices-demo.github.io/microservices-demo/deployment/kubernetes-start.html).

Note that, if you use the complete-demo.yaml, you'll have to create the sock-shop namespace -- as complete-demo does not include it (#733).

**Comment by pidster** [comment]
For future reference: if anyone runs into this issue, please check that all of the containers/services are up and running. The `user-sim` container can start before the other services are ready.

**Comment by pidster** [comment]
Further testing: the `java.net.UnknownHostException` seems like a timing error - it's only reproducible in my D4M, or on very small EC2 instances where the services are slow to start up.

Closing, pending further info.
