### ISSUE TITLE
Frontend crashes when a user that is not logged in tries to access the shopping cart

### ISSUE THREAD

**Issue by ddrechse** [microservices-demo/microservices-demo#812]
The following is from user/index.js

Logs when a logged in user accesses their shopping cart

```
Request received: /cart, undefined
Customer ID: user
GET /cart 200 - ms - -
GET /catalogue?size=3 200 - ms - -
App Get Addr BODY = {"_embedded":{"address":[{"_links":{"address":{"href":"http://user/addresses/user:1"},"self":{"href":"http://user/addresses/user:1"}},"city":"Springfield","country":"USA","id":"user:1","number":"123","postcode":"12123","street":"Main St"}]}}
GET /address 200 - ms - -
App Get Card BODY = {"_embedded":{"card":[{"_links":{"card":{"href":"http://user/cards/user:1234"},"self":{"href":"http://user/cards/user:1234"}},"ccv":"123","expires":"12/19","id":"user:1234","longNum":"************1234"}]}}
GET /card 200 - ms - -
```
And when a user that is not logged in attempts to access the cart

```
Request received: /cart, undefined
Customer ID: HI7gJQ2U7ED2v4yuZB7vS3kgZolgQOyg
GET /cart 200 - ms - -
GET /catalogue?size=3 200 - ms - -
App Get Addr BODY = 
undefined:1



SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.request.bind.res (/usr/src/app/api/user/index.js:100:29)
    at Request.self.callback (/usr/src/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! microservices-demo-front-end@0.0.1 start: `node server.js`
npm ERR! Exit status 1

```

**Comment by ddrechse** [comment]
I am using Helidon implementation of sockshop.  I am going to check that against the weaveworks implementation of user.  Closing this for now
