### ISSUE TITLE
logging is deprecated?

### ISSUE THREAD

**Issue by ntlzthm8** [microservices-demo/microservices-demo#870]
Hi!)
I fix efk logging manifest, it's working, but elastic have no data.

where i can configure fluentd or get any config maps to retrive data from microservices?

**Comment by ntlzthm8** [comment]
errors on fluentd

```
2021-07-27 09:05:13 +0000 [info]: Connection opened to Elasticsearch cluster => {:host=>"elasticsearch", :port=>9200, :scheme=>"http"}
2021-07-27 09:05:13 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2021-07-27 09:05:44 +0000 error_class="Elasticsearch::Transport::Transport::Errors::NotAcceptable" error="[406] {\"error\":\"Content-Type header [] is not supported\",\"status\":406}" plugin_id="object:2b04d7ad4d80"
  2021-07-27 09:05:13 +0000 [warn]: /home/fluent/.gem/ruby/2.3.0/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/transport/base.rb:201:in `__raise_transport_error'
  2021-07-27 09:05:13 +0000 [warn]: /home/fluent/.gem/ruby/2.3.0/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/transport/base.rb:312:in `perform_request'
  2021-07-27 09:05:13 +0000 [warn]: /home/fluent/.gem/ruby/2.3.0/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
  2021-07-27 09:05:13 +0000 [warn]: /home/fluent/.gem/ruby/2.3.0/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/client.rb:128:in `perform_request'
  2021-07-27 09:05:13 +0000 [warn]: /home/fluent/.gem/ruby/2.3.0/gems/elasticsearch-api-1.0.18/lib/elasticsearch/api/actions/bulk.rb:90:in `bulk'
  2021-07-27 09:05:13 +0000 [warn]: /home/fluent/.gem/ruby/2.3.0/gems/fluent-plugin-elasticsearch-1.9.2/lib/fluent/plugin/out_elasticsearch.rb:353:in `send_bulk'
  2021-07-27 09:05:13 +0000 [warn]: /home/fluent/.gem/ruby/2.3.0/gems/fluent-plugin-elasticsearch-1.9.2/lib/fluent/plugin/out_elasticsearch.rb:339:in `write_objects'
  2021-07-27 09:05:13 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.32/lib/fluent/output.rb:490:in `write'
  2021-07-27 09:05:13 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.32/lib/fluent/buffer.rb:354:in `write_chunk'
  2021-07-27 09:05:13 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.32/lib/fluent/buffer.rb:333:in `pop'
  2021-07-27 09:05:13 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.32/lib/fluent/output.rb:342:in `try_flush'
  2021-07-27 09:05:13 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.32/lib/fluent/output.rb:149:in `run'
2021-07-27 09:05:19 +0000 [info]: detected rotation of /var/lib/docker/containers/bb7aa46a866cd15630d86982462ca1d133464f0b6e1e08b0be20c9fa9d969e7a/bb7aa46a866cd15630d86982462ca1d133464f0b6e1e08b0be20c9fa9d969e7a-json.log; waiting 5 seconds
2021-07-27 09:05:44 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2021-07-27 09:06:50 +0000 error_class="Elasticsearch::Transport::Transport::Errors::NotAcceptable" error="[406] {\"error\":\"Content-Type header [] is not supported\",\"status\":406}" plugin_id="object:2b04d7ad4d80"
  2021-07-27 09:05:44 +0000 [warn]: suppressed same stacktrace
2021-07-27 09:06:50 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2021-07-27 09:09:06 +0000 error_class="Elasticsearch::Transport::Transport::Errors::NotAcceptable" error="[406] {\"error\":\"Content-Type header [] is not supported\",\"status\":406}" plugin_id="object:2b04d7ad4d80"
  2021-07-27 09:06:50 +0000 [warn]: suppressed same stacktrace
2021-07-27 09:09:06 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2021-07-27 09:12:53 +0000 error_class="Elasticsearch::Transport::Transport::Errors::NotAcceptable" error="[406] {\"error\":\"Content-Type header [] is not supported\",\"status\":406}" plugin_id="object:2b04d7ad4d80"
  2021-07-27 09:09:06 +0000 [warn]: suppressed same stacktrace
2021-07-27 09:12:53 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2021-07-27 09:20:26 +0000 error_class="Elasticsearch::Transport::Transport::Errors::NotAcceptable" error="[406] {\"error\":\"Content-Type header [] is not supported\",\"status\":406}" plugin_id="object:2b04d7ad4d80"
  2021-07-27 09:12:53 +0000 [warn]: suppressed same stacktrace
2021-07-27 09:20:26 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2021-07-27 09:39:19 +0000 error_class="Elasticsearch::Transport::Transport::Errors::NotAcceptable" error="[406] {\"error\":\"Content-Type header [] is not supported\",\"status\":406}" plugin_id="object:2b04d7ad4d80"
  2021-07-27 09:20:26 +0000 [warn]: suppressed same stacktrace

```

**Comment by ntlzthm8** [comment]
oh. you use fluentd 0.12 and elactic plugin is very old
i am add elastic 7+iamge  version to manifest
it's not compatibility :)

**Comment by giannoul** [comment]
@TidalPoo The error you mentioned:

```
2021-07-27 09:05:13 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2021-07-27 09:05:44 +0000 error_class="Elasticsearch::Transport::Transport::Errors::NotAcceptable" error="[406] {\"error\":\"Content-Type header [] is not supported\",\"status\":406}" plugin_id="object:2b04d7ad4d80"
```

has also a reference here:
* https://github.com/uken/fluent-plugin-elasticsearch/issues/268

The `fluentd` used comes from [weaveworksdemos/log-server](https://hub.docker.com/layers/weaveworksdemos/log-server/latest/images/sha256-e71a4ee33f708b9bb0d1851c983040fae5731deafb28985068aff10c01ba0f90?context=explore) and we may find its repository here:
* https://github.com/microservices-demo/log-server/blob/master/Dockerfile

The `fluentd` used in the docker image [weaveworksdemos/log-server](https://hub.docker.com/layers/weaveworksdemos/log-server/latest/images/sha256-e71a4ee33f708b9bb0d1851c983040fae5731deafb28985068aff10c01ba0f90?context=explore) seems to be the [fluent/fluentd:v0.12.32](https://hub.docker.com/layers/fluent/fluentd/v0.12.32/images/sha256-d6266e6be06a23bcdb4199cb8eb496b0bd2d4c14de4a0545686e77ea0545bb0b?context=explore) that you mentioned.

Taking the above into account, one version of `ElasticSearch` and `Kibana` I was able to use was `5.3.2`.

If an upgrade is to be be done here for the `ElasticSearch` and `Kibana` versions, we seem to need a newer version of [microservices-demo/log-server](https://github.com/microservices-demo/log-server) that will be based after a newer version of the `fluent/fluentd:latest-onbuild` image.

Regarding the configuration of `fluentd`, one way to do it is via a `configmap` that you can mount in the container. For example, the following `configmap`:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-custom-config
  namespace: kube-system
data:  
  custom.conf: |
    <source>
       type tail
       path /var/lib/docker/containers/*.log
       pos_file Fluentd-docker.pos
       time_format %Y-%m-%dT%H:%M:%S
       tag kubernetes.*
       format json
       time_key time
       read_from_head true
    </source>
    
    <filter kubernetes.var.lib.docker.containers.*.*.log>
       type kubernetes_metadata
    </filter>
    
    <match **>
      type copy
      <store>
        type elasticsearch
        host elasticsearch.kube-system.svc.cluster.local
        port 9200
        logstash_format true
        flush_interval 5s
      </store>
    </match>
```

can be mounted on the container like so:

```
    spec:
      serviceAccountName: fluentd
      containers:
       - image: weaveworksdemos/log-server
         name: fluentd
         env:
         - name: FLUENTD_CONF
           value: elk-custom/custom.conf
         volumeMounts:
         - name: fluentd-custom-config-vol
           mountPath: /fluentd/etc/elk-custom
.
.
.
      volumes:
      - name: fluentd-custom-config-vol
        configMap: 
          name: fluentd-custom-config
```

The above actually mounts the configmap as a file named `custom.conf` within the container in the path `/fluentd/etc/elk-custom/custom.conf` and instructs fluentd to use it. The details on how the container fluentd starts its process can be [seen here](https://hub.docker.com/layers/weaveworksdemos/log-server/latest/images/sha256-e71a4ee33f708b9bb0d1851c983040fae5731deafb28985068aff10c01ba0f90?context=explore) on line 32:
> CMD ["/bin/sh" "-c" "exec fluentd -c /fluentd/etc/$FLUENTD_CONF -p /fluentd/plugins $FLUENTD_OPT"]

**Comment by ntlzthm8** [comment]
5.3.2 - this is what you need. But, I already did it differently, and connected elastic amp monitoring
